Addition with data vectors

In [ ]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [ ]:
c(2,3,5,7) + c(-2,-3, -5, 8)

[1]  0  0  0 15

R as a calculator

In [ ]:
2^3

[1] 8

In [ ]:
2**3

[1] 8

In [ ]:
2^0.5

[1] 1.414214

In [ ]:
2**0.5

[1] 1.414214

In [ ]:
2^-0.5

[1] 0.7071068

Power operator with scalar

In [ ]:
c(2,3,5,7)^2

[1]  4  9 25 49

Power operation with vector

In [ ]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [ ]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [ ]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

Integer division with scalar

In [ ]:
2 %/% 2

[1] 1

In [ ]:
5 %/% 2

[1] 2

In [ ]:
7 %/% 3

[1] 2

Integer division with data vector

In [ ]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [ ]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [ ]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Modulo Division (x mod y) with scalars

In [ ]:
2 %% 2

[1] 0

In [ ]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [ ]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [ ]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

Maximum

In [ ]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [ ]:
max( c(1.2, 3.4, -7.8) )

[1] 3.4

Minimum

In [ ]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [ ]:
min( c(1.2, 3.4, -7.8) )

[1] -7.8

Arithmetic mean

In [ ]:
mean(2, 3, 4)

[1] 2

In [ ]:
mean(c(2, 3, 4))

[1] 3

Overview Over Further Functions

In [ ]:
abs(-4)

[1] 4

In [ ]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

In [ ]:
sqrt(4)

[1] 2

In [ ]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

In [ ]:
sum(c(2,3,5,7))

[1] 17

In [ ]:
prod(c(2,3,5,7))

[1] 210

In [ ]:
round(1.23)

[1] 1

In [ ]:
round(1.83)

[1] 2

In [ ]:
log(10)

[1] 2.302585

In [ ]:
log(exp(1))

[1] 1

In [ ]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [ ]:
log10(10)

[1] 1

In [ ]:
log10(100)

[1] 2

In [ ]:
log10(c(10, 100, 1000))

[1] 1 2 3

In [ ]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [ ]:
x2 = x1^2

x2

[1]  1  4  9 16

In [ ]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [ ]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

In [ ]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8) )

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
x[3,2]

[1] 7

In [ ]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

OR

In [ ]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = FALSE)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
y = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8) )

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
dim(x)

[1] 4 2

In [ ]:
nrow(x)

[1] 4

In [ ]:
ncol(x)

[1] 2

In [ ]:
mode(x)

[1] "numeric"

In [ ]:
attributes(x)

$dim
[1] 4 2

In [ ]:
help("matrix")